// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});

// import { PrismaPg } from "@prisma/adapter-pg";
// import "dotenv/config";

// export const prismaConfig = {
//   adapter: new PrismaPg({
//     connectionString: process.env.DATABASE_URL!,
//   }),
// };

// import { PrismaClient } from "../../generated/prisma"; // path to generated client
// import { prismaConfig } from "../../prisma/prisma.config";

// const prisma = new PrismaClient(prismaConfig);

// export { prisma };
